- name: install nginx
  hosts: install
  become: yes
  tasks:
  - name: Installing nginx server
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: starting nginx server
    ansible.builtin.package:
      name: nginx
      state: present
      enabled: yes