- name: vars from file
  hosts: localhost
  connection: local
  vars_files: 
  - vars.yaml
  tasks:
  - name: Fetching vars from file
    vars: 
      NAME: "Bingi"
    ansible.builtin.debug:
      msg: "I am {{ NAME }}, and i am learning {{ COURSE }} which is {{ Description }}"